### ISSUE TITLE
Refactor input.rs for licences

### ISSUE THREAD

**Issue by botika** [rust-iendo/yarte#14]
For licenses I will look for another way to take syn's arguments, for example a visit with syn. #5

**Comment by Lucretiel** [comment]
You're missing the point I think. There is no amount of refactoring you can do that will make this NOT a fork of Askama, so there's no amount of refactoring that will relieve you of the legal obligation to do the VERY SIMPLE TASK of adding a copy of Askama's MIT license to your directory somewhere.

**Comment by botika** [comment]
So to your understanding, can not be closed with this pull request?

**Comment by botika** [comment]
@Lucretiel any ping? your bored? something that decor on the code, or have you returned to reddit?

**Comment by Lucretiel** [comment]
> So to your understanding, can not be closed with this pull request?

I don't understand the question, because this issue (#14) is not a Pull Request. However, if your question is "does this proposed refactor resolve #5", the answer is no.

**Comment by botika** [comment]
#23

**Comment by botika** [comment]
It seems that it gets bored, it does not offer any improvement to the quality of the project and it makes me waste my time. Step to close? @Lucretiel any ping with this issue and merged code?
